var searchData=
[
  ['hand_0',['hand',['../class_hx_hand.html#ae4c973da564cb8a45ef47d8ed29a4feb',1,'HxHand']]],
  ['hand_5f_1',['hand_',['../class_a_hx_hand_actor.html#abce2bd4496d6d4f9c8a53e7ed755c6f8',1,'AHxHandActor']]],
  ['hand_5fanim_5foptimization_5fmode_5f_2',['hand_anim_optimization_mode_',['../class_a_hx_hand_actor.html#a0186d0ec0b6c056739b80adf2fec5afb',1,'AHxHandActor']]],
  ['hand_5fanimation_5fhelpers_2eh_3',['hand_animation_helpers.h',['../hand__animation__helpers_8h.html',1,'']]],
  ['hand_5fanimation_5fmode_5f_4',['hand_animation_mode_',['../class_a_hx_core_actor.html#a06af791cd2a79adfb4d347724ba36946',1,'AHxCoreActor::hand_animation_mode_'],['../class_a_hx_hand_actor.html#a6b1a81bff7419221154cf2963edbaad3',1,'AHxHandActor::hand_animation_mode_']]],
  ['hand_5fbreadth_5flimit_5fupper_5fm_5',['hand_breadth_limit_upper_m',['../struct_haptx_api_1_1_glove.html#a8c003cc8e232ccc1e526c371c1442778',1,'HaptxApi::Glove']]],
  ['hand_5flength_5flimit_5fupper_5fm_6',['hand_length_limit_upper_m',['../struct_haptx_api_1_1_glove.html#a7884e03d89976ee8e9d54e8aae3a8884',1,'HaptxApi::Glove']]],
  ['hand_5fmodel_5fpreference_7',['hand_model_preference',['../struct_haptx_api_1_1_user_profile.html#ac93aa77d5eac4c1c79f0526e9536b3ab',1,'HaptxApi::UserProfile']]],
  ['hand_5fscale_5ffactor_5f_8',['hand_scale_factor_',['../class_a_hx_hand_actor.html#a873b0c5127fc743578c4bc455001fdf9',1,'AHxHandActor']]],
  ['handanimationconfig_9',['HandAnimationConfig',['../class_hand_animation_config.html',1,'']]],
  ['handanimationfailstrategy_10',['HandAnimationFailStrategy',['../_hx_core_8cs.html#ab629ddbe491a7d41a6fe9a0a55a1c15c',1,'HandAnimationFailStrategy:&#160;HxCore.cs'],['../hx__core__actor_8h.html#ab6b0d16e1e93a136d90a57962efab33c',1,'HandAnimationFailStrategy:&#160;hx_core_actor.h']]],
  ['handanimationmode_11',['handAnimationMode',['../class_hx_core.html#ad389e4be43dd76d760b2ede563ad93da',1,'HxCore.handAnimationMode'],['../class_hx_hand.html#aba772072f8718a12727d4131fbd2e18d',1,'HxHand.handAnimationMode']]],
  ['handanimationmode_12',['HandAnimationMode',['../_hx_core_8cs.html#aad7073ee0801d0380ef279f93dee1eaa',1,'HandAnimationMode:&#160;HxCore.cs'],['../hx__core__actor_8h.html#aa3e09f4329bd69126b51642efe29165f',1,'HandAnimationMode:&#160;hx_core_actor.h']]],
  ['handanimationoptimizationmode_13',['HandAnimationOptimizationMode',['../_hx_hand_8cs.html#ad1e09a8d2806608a89d201cd99011ebb',1,'HxHand.cs']]],
  ['handanimationvisualizer_14',['handAnimationVisualizer',['../class_hx_hand.html#a806dad9ea9e7f31cceea1c30fc833bfd',1,'HxHand']]],
  ['handanimationvisualizer2_15',['handAnimationVisualizer2',['../class_hx_hand.html#a0cf341d68c277c7fd5dfb5978d17d83d',1,'HxHand']]],
  ['handanimoptimizationmode_16',['handAnimOptimizationMode',['../class_hx_hand.html#ab12aa28b8284aecc0a3b016c9624aa5c',1,'HxHand']]],
  ['handedness_17',['handedness',['../struct_haptx_api_1_1_glove.html#a8f8e8f7eedfb42d4f585666d4ef26788',1,'HaptxApi::Glove']]],
  ['handjointrots_18',['HandJointRots',['../namespace_haptx_api.html#a9db3cfa304e876828197bf81dc233ee0',1,'HaptxApi']]],
  ['handling_19',['API Error Handling',['../page_api_error_handling.html',1,'']]],
  ['handmaterials_20',['HandMaterials',['../struct_hx_hand_1_1_hand_materials.html',1,'HxHand']]],
  ['handmaterials_21',['handMaterials',['../class_hx_hand.html#a8384b75c99eaee1328a2758cc649a8ed',1,'HxHand']]],
  ['handmeshes_22',['HandMeshes',['../struct_hx_hand_1_1_hand_meshes.html',1,'HxHand']]],
  ['handmeshes_23',['handMeshes',['../class_hx_hand.html#a6cffe5432febe5054317b94a03a652ca',1,'HxHand']]],
  ['handmodelpreference_24',['HandModelPreference',['../namespace_haptx_api.html#ae6afc5cb538589d33dc9cb6a97e74690',1,'HaptxApi']]],
  ['handphysicsstate_25',['HandPhysicsState',['../struct_hx_hand_1_1_hand_physics_state.html',1,'HxHand']]],
  ['handphysicstargets_26',['HandPhysicsTargets',['../struct_hx_hand_1_1_hand_physics_targets.html',1,'HxHand']]],
  ['handscalefactor_27',['HandScaleFactor',['../class_hx_hand.html#a8467a150cea83e185fb276ed6f110957',1,'HxHand']]],
  ['haptic_20effect_20tuning_28',['Haptic Effect Tuning',['../page_unity_plugin_summary.html#section_unity_haptic_effect_tuning',1,'Haptic Effect Tuning'],['../page_unreal_plugin_summary.html#section_unreal_haptic_effect_tuning',1,'Haptic Effect Tuning']]],
  ['haptic_20effects_29',['Haptic Effects',['../group__group__haptic__effects.html',1,'Haptic Effects'],['../page_unity_plugin_summary.html#section_unity_haptic_effects',1,'Haptic Effects'],['../page_unreal_plugin_summary.html#section_unreal_haptic_effects',1,'Haptic Effects']]],
  ['haptic_20primitive_20blueprints_30',['Haptic Primitive Blueprints',['../page_unreal_plugin_summary.html#section_unreal_haptic_primitive_blueprints',1,'']]],
  ['haptic_20primitive_20prefabs_31',['Haptic Primitive Prefabs',['../page_unity_plugin_summary.html#section_unity_haptic_primitive_prefabs',1,'']]],
  ['haptic_20primitive_20summary_32',['Haptic Primitive Summary',['../page_unity_haptic_primitive_summary.html',1,'Unity Haptic Primitive Summary'],['../page_unreal_haptic_primitive_summary.html',1,'Unreal Haptic Primitive Summary']]],
  ['haptic_20primitives_33',['Haptic Primitives',['../group__group__unity__haptic__primitives.html',1,'Unity Haptic Primitives'],['../group__group__unreal__haptic__primitives.html',1,'Unreal Haptic Primitives']]],
  ['haptic_5feffect_2eh_34',['haptic_effect.h',['../haptic__effect_8h.html',1,'']]],
  ['haptic_5fframe_2eh_35',['haptic_frame.h',['../haptic__frame_8h.html',1,'']]],
  ['hapticeffect_36',['HapticEffect',['../class_haptx_api_1_1_haptic_effect.html',1,'HaptxApi::HapticEffect'],['../class_haptx_api_1_1_haptic_effect.html#a22671f7b3d188c309cdd82516770504e',1,'HaptxApi::HapticEffect::HapticEffect(const HapticEffect &amp;)=delete'],['../class_haptx_api_1_1_haptic_effect.html#afb15ddbaeb52103f4b288c05ddcb17ed',1,'HaptxApi::HapticEffect::HapticEffect(HapticEffect &amp;&amp;)=delete'],['../class_haptx_api_1_1_haptic_effect.html#a51af7d63874b35b6328ebb5a999f8a71',1,'HaptxApi::HapticEffect::HapticEffect()']]],
  ['hapticframe_37',['HapticFrame',['../struct_haptx_api_1_1_haptic_frame.html',1,'HaptxApi::HapticFrame'],['../struct_haptx_api_1_1_haptic_frame.html#ac60cdc130e302f20ced6cbe281c65424',1,'HaptxApi::HapticFrame::HapticFrame()']]],
  ['haptics_20stack_38',['Haptics stack',['../page_api_overview.html#section_haptics_stack',1,'']]],
  ['haptx_20airpack_20to_20wi_20fi_39',['Connecting a HaptX Airpack to Wi-Fi',['../page_haptx_dashboard.html#section_wireless_setup',1,'']]],
  ['haptx_20api_20libraries_20headers_20and_20documentation_40',['HaptX API libraries, headers, and documentation',['../page_install.html#section_install_libs',1,'']]],
  ['haptx_20dashboard_41',['HaptX Dashboard',['../page_haptx_dashboard.html',1,'']]],
  ['haptx_20enabled_20simulation_42',['The typical HaptX-enabled simulation',['../page_api_overview.html#section_the_typical_haptx_enabled_simulation',1,'']]],
  ['haptx_20sdk_20main_20page_43',['HaptX SDK Main Page',['../index.html',1,'']]],
  ['haptx_20system_44',['HaptX System',['../group__group__haptx__system.html',1,'']]],
  ['haptx_5fname_2eh_45',['haptx_name.h',['../haptx__name_8h.html',1,'']]],
  ['haptx_5fprimitives_5fshared_2eh_46',['haptx_primitives_shared.h',['../haptx__primitives__shared_8h.html',1,'']]],
  ['haptx_5fsystem_2eh_47',['haptx_system.h',['../haptx__system_8h.html',1,'']]],
  ['haptx_5fuuid_2eh_48',['haptx_uuid.h',['../haptx__uuid_8h.html',1,'']]],
  ['haptxapi_49',['HaptxApi',['../namespace_haptx_api.html',1,'']]],
  ['haptxapi_3a_3aalternatehandik_50',['AlternateHandIk',['../namespace_haptx_api_1_1_alternate_hand_ik.html',1,'HaptxApi']]],
  ['haptxapi_3a_3aavataranimationoptimizer_51',['AvatarAnimationOptimizer',['../namespace_haptx_api_1_1_avatar_animation_optimizer.html',1,'HaptxApi']]],
  ['haptxapi_3a_3adefaulthandik_52',['DefaultHandIk',['../namespace_haptx_api_1_1_default_hand_ik.html',1,'HaptxApi']]],
  ['haptxapi_3a_3adirectpneumaticcalculator_53',['DirectPneumaticCalculator',['../namespace_haptx_api_1_1_direct_pneumatic_calculator.html',1,'HaptxApi']]],
  ['haptxapi_3a_3aenums_3a_3adetails_54',['details',['../namespace_haptx_api_1_1enums_1_1details.html',1,'HaptxApi::enums']]],
  ['haptxapi_3a_3alogging_55',['Logging',['../namespace_haptx_api_1_1_logging.html',1,'HaptxApi']]],
  ['haptxapi_3a_3aopenvrwrapper_56',['OpenvrWrapper',['../namespace_haptx_api_1_1_openvr_wrapper.html',1,'HaptxApi']]],
  ['haptxapi_3a_3apneumaticaddresser_57',['PneumaticAddresser',['../namespace_haptx_api_1_1_pneumatic_addresser.html',1,'HaptxApi']]],
  ['haptxapi_3a_3asimulatedgestures_58',['SimulatedGestures',['../namespace_haptx_api_1_1_simulated_gestures.html',1,'HaptxApi']]],
  ['haptxapi_3a_3asphericalfit_59',['SphericalFit',['../namespace_haptx_api_1_1_spherical_fit.html',1,'HaptxApi']]],
  ['haptxapi_3a_3athimblecompensator_60',['ThimbleCompensator',['../namespace_haptx_api_1_1_thimble_compensator.html',1,'HaptxApi']]],
  ['haptxapi_3a_3atrackerloader_61',['TrackerLoader',['../namespace_haptx_api_1_1_tracker_loader.html',1,'HaptxApi']]],
  ['haptxapi_3a_3aversion_62',['Version',['../namespace_haptx_api_1_1_version.html',1,'HaptxApi']]],
  ['haptxapi_3a_3aworldtransformcalculator_63',['WorldTransformCalculator',['../namespace_haptx_api_1_1_world_transform_calculator.html',1,'HaptxApi']]],
  ['haptxcore_20tt_20blueprint_64',['&lt;tt&gt;HaptxCore&lt;/tt&gt; Blueprint',['../page_unreal_plugin_summary.html#section_haptx_core_blueprint',1,'']]],
  ['haptxcore_20tt_20prefab_65',['&lt;tt&gt;HaptxCore&lt;/tt&gt; Prefab',['../page_unity_plugin_summary.html#section_haptx_core_prefab',1,'']]],
  ['haptxhand_20tt_20blueprint_66',['&lt;tt&gt;HaptxHand&lt;/tt&gt; Blueprint',['../page_unreal_plugin_summary.html#section_haptx_hand_blueprint',1,'']]],
  ['haptxhand_20tt_20prefab_67',['&lt;tt&gt;HaptxHand&lt;/tt&gt; Prefab',['../page_unity_plugin_summary.html#section_haptx_hand_prefab',1,'']]],
  ['haptxname_68',['HaptxName',['../class_haptx_api_1_1_haptx_name.html',1,'HaptxApi::HaptxName'],['../class_haptx_api_1_1_haptx_name.html#a66565e7384404a11af8fcd85a51b2d21',1,'HaptxApi::HaptxName::HaptxName()=default'],['../class_haptx_api_1_1_haptx_name.html#a054cf1a03b52588d7bea5d69a3da03f9',1,'HaptxApi::HaptxName::HaptxName(const std::string &amp;text)'],['../class_haptx_api_1_1_haptx_name.html#a04d718f9a0a8eb6cf6b9f0d1dc89a084',1,'HaptxApi::HaptxName::HaptxName(const std::string &amp;text, bool hash_now)'],['../class_haptx_api_1_1_haptx_name.html#aa385c039fce4e427402ae0c4317e15ad',1,'HaptxApi::HaptxName::HaptxName(const char *text)'],['../class_haptx_api_1_1_haptx_name.html#ab3b8d42234097d90e6b5ae502ac78a14',1,'HaptxApi::HaptxName::HaptxName(const char *text, bool hash_now)']]],
  ['haptxpawn_20tt_20blueprint_69',['&lt;tt&gt;HaptxPawn&lt;/tt&gt; Blueprint',['../page_unreal_plugin_summary.html#section_haptx_pawn_blueprint',1,'']]],
  ['haptxplayer_20tt_20prefab_70',['&lt;tt&gt;HaptxPlayer&lt;/tt&gt; Prefab',['../page_unity_plugin_summary.html#section_haptx_player_prefab',1,'']]],
  ['haptxprimitivedebugger_20tt_71',['&lt;tt&gt;HaptxPrimitiveDebugger&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_haptx_primitive_debugger',1,'']]],
  ['haptxsystem_72',['HaptxSystem',['../class_haptx_api_1_1_haptx_system.html',1,'HaptxApi::HaptxSystem'],['../class_hx_core.html#ab395650ecc1232548bff71a2b7573f7f',1,'HxCore.HaptxSystem'],['../class_haptx_api_1_1_haptx_system.html#a9b628b76d2f02258ad8adc78ddb1e692',1,'HaptxApi::HaptxSystem::HaptxSystem()'],['../class_haptx_api_1_1_haptx_system.html#a9b479372c33def10f68ec1ffe206a26c',1,'HaptxApi::HaptxSystem::HaptxSystem(const HaptxSystem &amp;other)=default'],['../class_haptx_api_1_1_haptx_system.html#ade2bec6ddf750b70e1f1bab56b7d0c1e',1,'HaptxApi::HaptxSystem::HaptxSystem(HaptxSystem &amp;&amp;other) noexcept=default']]],
  ['haptxuuid_73',['HaptxUuid',['../class_haptx_api_1_1_haptx_uuid.html',1,'HaptxApi::HaptxUuid'],['../class_haptx_api_1_1_haptx_uuid.html#a59c19f889de091a2b0988304a6ea49a5',1,'HaptxApi::HaptxUuid::HaptxUuid()'],['../class_haptx_api_1_1_haptx_uuid.html#ab809290af81b7e30ea499bcfa9275288',1,'HaptxApi::HaptxUuid::HaptxUuid(const std::string &amp;str)'],['../class_haptx_api_1_1_haptx_uuid.html#a17c8c5e6b2496868eed372f170ef22f5',1,'HaptxApi::HaptxUuid::HaptxUuid(const std::wstring &amp;str)']]],
  ['hardware_74',['hardware',['../page_unity_plugin_summary.html#section_hx_hand_script_simulated_vs_hardware',1,'Simulated vs. hardware'],['../page_unreal_plugin_summary.html#section_hx_hand_actor_simulated_vs_hardware',1,'Simulated vs. hardware'],['../page_haptx_dashboard.html#section_dashboard_simulation',1,'Using physical and simulated hardware']]],
  ['hardware_20visualizer_75',['Hardware Visualizer',['../page_haptx_dashboard.html#section_dashboard_visualizer_ui',1,'']]],
  ['hardware_5fdefinition_5fmetadata_2eh_76',['hardware_definition_metadata.h',['../hardware__definition__metadata_8h.html',1,'']]],
  ['hardwaredefinitionmetadata_77',['HardwareDefinitionMetadata',['../struct_haptx_api_1_1_hardware_definition_metadata.html',1,'HaptxApi']]],
  ['has_5fci_5fbody_5fid_78',['has_ci_body_id',['../struct_f_hx_hand_actor_bone_data.html#ab99a6a8a4d56db6c3347ba17d07ca059',1,'FHxHandActorBoneData']]],
  ['has_5fgd_5fbody_5fid_79',['has_gd_body_id',['../struct_f_hx_hand_actor_bone_data.html#a27a773554658b17e1a01a7b16ee9830b',1,'FHxHandActorBoneData']]],
  ['hash_3c_20haptxapi_3a_3ahaptxname_20_3e_80',['hash&lt; HaptxApi::HaptxName &gt;',['../structstd_1_1hash_3_01_haptx_api_1_1_haptx_name_01_4.html',1,'std']]],
  ['hash_3c_20haptxapi_3a_3ahaptxuuid_20_3e_81',['hash&lt; HaptxApi::HaptxUuid &gt;',['../structstd_1_1hash_3_01_haptx_api_1_1_haptx_uuid_01_4.html',1,'std']]],
  ['hash_3c_20haptxapi_3a_3apneumaticaddress_20_3e_82',['hash&lt; HaptxApi::PneumaticAddress &gt;',['../structstd_1_1hash_3_01_haptx_api_1_1_pneumatic_address_01_4.html',1,'std']]],
  ['hash_3c_20haptxapi_3a_3atransformcontext_20_3e_83',['hash&lt; HaptxApi::TransformContext &gt;',['../structstd_1_1hash_3_01_haptx_api_1_1_transform_context_01_4.html',1,'std']]],
  ['hashcode_84',['HashCode',['../class_hx_name.html#a527a0f50e231fd401d2c86a21685f3c8',1,'HxName']]],
  ['hasrelevantrules_85',['HasRelevantRules',['../class_hx_unity_settings_window.html#a51e465b7c5575e1b00680c9832687342',1,'HxUnitySettingsWindow']]],
  ['headers_20and_20documentation_86',['HaptX API libraries, headers, and documentation',['../page_install.html#section_install_libs',1,'']]],
  ['height_5fmax_5fm_87',['height_max_m',['../class_haptx_api_1_1_tactor.html#aa07d3fe78d60ede6b7a77631798b5529',1,'HaptxApi::Tactor']]],
  ['height_5fmin_5fm_88',['height_min_m',['../class_haptx_api_1_1_tactor.html#ad6b743f03e58bf61d6b58094f52131ec',1,'HaptxApi::Tactor']]],
  ['height_5ftarget_5fscale_89',['height_target_scale',['../struct_f_tactile_feedback_visualization_parameters.html#ad820e62abccde09c25b3298791048193',1,'FTactileFeedbackVisualizationParameters']]],
  ['heighttargetscale_90',['heightTargetScale',['../class_hx_patch_1_1_tactile_feedback_visualizer.html#a7792f6e351678bb289eaf0f98fedebe1',1,'HxPatch::TactileFeedbackVisualizer']]],
  ['high_5ftransition_5fposition_5f_91',['high_transition_position_',['../class_u_hx3_state_function.html#aa46b36569db30467d53baa65629b94f6',1,'UHx3StateFunction']]],
  ['highangularxlimit_92',['highAngularXLimit',['../class_hx_core_1_1_angular_anchor_constraint_settings.html#a9d353d393e07c5e06c451d685bd2afbe',1,'HxCore.AngularAnchorConstraintSettings.highAngularXLimit'],['../class_configurable_joint_parameters.html#a75579f1bc46322791cba2d67f6c43369',1,'ConfigurableJointParameters.highAngularXLimit']]],
  ['hightransitionposition_93',['highTransitionPosition',['../class_hx3_state_function.html#ae537876146509d166af80fb925a99355',1,'Hx3StateFunction.highTransitionPosition'],['../class_hx3_state_function_serialized.html#aa519b78b2e5eaaf6ea8391db96037fb0',1,'Hx3StateFunctionSerialized.highTransitionPosition']]],
  ['hints_94',['hints',['../struct_haptx_api_1_1_anim_frame.html#a99cc7068140ff978f62a8deaeba1fb2c',1,'HaptxApi::AnimFrame::hints'],['../struct_haptx_api_1_1_mocap_frame.html#ad883469cdb8cedbe8a73a082879ba79b',1,'HaptxApi::MocapFrame::hints'],['../struct_f_hx_hand_animation_hint.html#a23358673800d823bce5f102fb236c8bc',1,'FHxHandAnimationHint::hints']]],
  ['history_95',['History',['../page_legacy_version_history.html',1,'Legacy Version History'],['../page_version_history.html',1,'Version History']]],
  ['homeenvvar_96',['HomeEnvVar',['../class_hx_shared.html#ad3ef5c3d9fe8f15a9a9c64e9353e5814',1,'HxShared']]],
  ['http_5ferror_5f400_97',['HTTP_ERROR_400',['../namespace_haptx_api.html#af85a5c0d6caf8c683e4c165a6e81bd4fa534468a00738674d9a04c84593593555',1,'HaptxApi']]],
  ['http_5ferror_5f401_98',['HTTP_ERROR_401',['../namespace_haptx_api.html#af85a5c0d6caf8c683e4c165a6e81bd4fa97e8992bd59e8c08b8d27434eb883413',1,'HaptxApi']]],
  ['http_5ferror_5f403_99',['HTTP_ERROR_403',['../namespace_haptx_api.html#af85a5c0d6caf8c683e4c165a6e81bd4fa8ac437c61a932c4bcbbb8c98837319d8',1,'HaptxApi']]],
  ['http_5ferror_5f404_100',['HTTP_ERROR_404',['../namespace_haptx_api.html#af85a5c0d6caf8c683e4c165a6e81bd4faffd0dbcbcb5c877fd3f6ee84a2980cfd',1,'HaptxApi']]],
  ['http_5ferror_5f408_101',['HTTP_ERROR_408',['../namespace_haptx_api.html#af85a5c0d6caf8c683e4c165a6e81bd4fa0339cfcd97887da33352462e070debe7',1,'HaptxApi']]],
  ['hx1djoint_102',['Hx1DJoint',['../class_hx1_d_joint.html',1,'']]],
  ['hx1djoint_2ecs_103',['Hx1DJoint.cs',['../_hx1_d_joint_8cs.html',1,'']]],
  ['hx1djointeditor_104',['Hx1DJointEditor',['../class_hx1_d_joint_editor.html',1,'']]],
  ['hx1djointeditor_2ecs_105',['Hx1DJointEditor.cs',['../_hx1_d_joint_editor_8cs.html',1,'']]],
  ['hx1drotator_106',['Hx1DRotator',['../class_hx1_d_rotator.html',1,'']]],
  ['hx1drotator_20tt_107',['&lt;tt&gt;Hx1DTranslator&lt;/tt&gt; and &lt;tt&gt;Hx1DRotator&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_hx_1d_components',1,'']]],
  ['hx1drotator_2ecs_108',['Hx1DRotator.cs',['../_hx1_d_rotator_8cs.html',1,'']]],
  ['hx1drotatoreditor_109',['Hx1DRotatorEditor',['../class_hx1_d_rotator_editor.html',1,'']]],
  ['hx1dtranslator_110',['Hx1DTranslator',['../class_hx1_d_translator.html',1,'']]],
  ['hx1dtranslator_20tt_20and_20tt_20hx1drotator_20tt_111',['&lt;tt&gt;Hx1DTranslator&lt;/tt&gt; and &lt;tt&gt;Hx1DRotator&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_hx_1d_components',1,'']]],
  ['hx1dtranslator_2ecs_112',['Hx1DTranslator.cs',['../_hx1_d_translator_8cs.html',1,'']]],
  ['hx1dtranslatoreditor_113',['Hx1DTranslatorEditor',['../class_hx1_d_translator_editor.html',1,'']]],
  ['hx2statefunction_114',['Hx2StateFunction',['../class_hx2_state_function.html',1,'Hx2StateFunction'],['../class_hx2_state_function.html#aa7d8eebbca93be1dcf4a7299dda98bd0',1,'Hx2StateFunction.Hx2StateFunction()']]],
  ['hx2statefunctionserialized_115',['Hx2StateFunctionSerialized',['../class_hx2_state_function_serialized.html',1,'']]],
  ['hx3statefunction_116',['Hx3StateFunction',['../class_hx3_state_function.html',1,'Hx3StateFunction'],['../class_hx3_state_function.html#aff78b0e4bcd626fe0ebbe88e5b5117bf',1,'Hx3StateFunction.Hx3StateFunction()']]],
  ['hx3statefunctionserialized_117',['Hx3StateFunctionSerialized',['../class_hx3_state_function_serialized.html',1,'']]],
  ['hx_5f1d_5fconstraint_5fcomponent_2eh_118',['hx_1d_constraint_component.h',['../hx__1d__constraint__component_8h.html',1,'']]],
  ['hx_5f1d_5frotator_5fcomponent_2eh_119',['hx_1d_rotator_component.h',['../hx__1d__rotator__component_8h.html',1,'']]],
  ['hx_5f1d_5ftranslator_5fcomponent_2eh_120',['hx_1d_translator_component.h',['../hx__1d__translator__component_8h.html',1,'']]],
  ['hx_5fbounding_5fvolumes_2eh_121',['hx_bounding_volumes.h',['../hx__bounding__volumes_8h.html',1,'']]],
  ['hx_5fconstraint_5fcomponent_2eh_122',['hx_constraint_component.h',['../hx__constraint__component_8h.html',1,'']]],
  ['hx_5fconstraint_5finstance_5f_123',['hx_constraint_instance_',['../class_u_hx_constraint_component.html#ab81963b5453fc808daee7ff3991cedeb',1,'UHxConstraintComponent']]],
  ['hx_5fcore_5factor_2eh_124',['hx_core_actor.h',['../hx__core__actor_8h.html',1,'']]],
  ['hx_5fcurve_5fdirect_5feffect_5fcomponent_2eh_125',['hx_curve_direct_effect_component.h',['../hx__curve__direct__effect__component_8h.html',1,'']]],
  ['hx_5fcurve_5fobject_5feffect_5fcomponent_2eh_126',['hx_curve_object_effect_component.h',['../hx__curve__object__effect__component_8h.html',1,'']]],
  ['hx_5fcurve_5fspatial_5feffect_5fcomponent_2eh_127',['hx_curve_spatial_effect_component.h',['../hx__curve__spatial__effect__component_8h.html',1,'']]],
  ['hx_5fdebug_5fdraw_5fsystem_2eh_128',['hx_debug_draw_system.h',['../hx__debug__draw__system_8h.html',1,'']]],
  ['hx_5fdirect_5feffect_5fcomponent_2eh_129',['hx_direct_effect_component.h',['../hx__direct__effect__component_8h.html',1,'']]],
  ['hx_5fdof_2eh_130',['hx_dof.h',['../hx__dof_8h.html',1,'']]],
  ['hx_5fdof_5fbehavior_2eh_131',['hx_dof_behavior.h',['../hx__dof__behavior_8h.html',1,'']]],
  ['hx_5fdof_5fdetent_5fbehavior_2eh_132',['hx_dof_detent_behavior.h',['../hx__dof__detent__behavior_8h.html',1,'']]],
  ['hx_5fglobal_5fsettings_2eh_133',['hx_global_settings.h',['../hx__global__settings_8h.html',1,'']]],
  ['hx_5fhand_5factor_2eh_134',['hx_hand_actor.h',['../hx__hand__actor_8h.html',1,'']]],
  ['hx_5fhand_5factor_5fstructs_2eh_135',['hx_hand_actor_structs.h',['../hx__hand__actor__structs_8h.html',1,'']]],
  ['hx_5fhaptic_5feffect_5fcomponent_2eh_136',['hx_haptic_effect_component.h',['../hx__haptic__effect__component_8h.html',1,'']]],
  ['hx_5fobject_5feffect_5fcomponent_2eh_137',['hx_object_effect_component.h',['../hx__object__effect__component_8h.html',1,'']]],
  ['hx_5foffset_5ftuner_5fcomponent_2eh_138',['hx_offset_tuner_component.h',['../hx__offset__tuner__component_8h.html',1,'']]],
  ['hx_5fon_5fscreen_5flog_2eh_139',['hx_on_screen_log.h',['../hx__on__screen__log_8h.html',1,'']]],
  ['hx_5fpatch_5fcomponent_2eh_140',['hx_patch_component.h',['../hx__patch__component_8h.html',1,'']]],
  ['hx_5fphysical_5fmaterial_2eh_141',['hx_physical_material.h',['../hx__physical__material_8h.html',1,'']]],
  ['hx_5fphysical_5fmaterial_5ffactory_2eh_142',['hx_physical_material_factory.h',['../hx__physical__material__factory_8h.html',1,'']]],
  ['hx_5fphysical_5fmodels_2eh_143',['hx_physical_models.h',['../hx__physical__models_8h.html',1,'']]],
  ['hx_5fsimulation_5fcallbacks_2eh_144',['hx_simulation_callbacks.h',['../hx__simulation__callbacks_8h.html',1,'']]],
  ['hx_5fspatial_5feffect_5fcomponent_2eh_145',['hx_spatial_effect_component.h',['../hx__spatial__effect__component_8h.html',1,'']]],
  ['hx_5fspatial_5feffect_5fcomponent_5fvisualizer_2eh_146',['hx_spatial_effect_component_visualizer.h',['../hx__spatial__effect__component__visualizer_8h.html',1,'']]],
  ['hx_5fstate_5ffunctions_2eh_147',['hx_state_functions.h',['../hx__state__functions_8h.html',1,'']]],
  ['hx_5fsurface_5fcomponent_2eh_148',['hx_surface_component.h',['../hx__surface__component_8h.html',1,'']]],
  ['hx_5fwave_5fdirect_5feffect_5fcomponent_2eh_149',['hx_wave_direct_effect_component.h',['../hx__wave__direct__effect__component_8h.html',1,'']]],
  ['hx_5fwave_5fobject_5feffect_5fcomponent_2eh_150',['hx_wave_object_effect_component.h',['../hx__wave__object__effect__component_8h.html',1,'']]],
  ['hx_5fwave_5fspatial_5feffect_5fcomponent_2eh_151',['hx_wave_spatial_effect_component.h',['../hx__wave__spatial__effect__component_8h.html',1,'']]],
  ['hxactiveinputhandlingrule_152',['HxActiveInputHandlingRule',['../class_hx_active_input_handling_rule.html',1,'']]],
  ['hxactiveinputhandlingrule_2ecs_153',['HxActiveInputHandlingRule.cs',['../_hx_active_input_handling_rule_8cs.html',1,'']]],
  ['hxairpackinput_154',['/HxAirpackInput',['../page_ros_node_summary.html#section_hx_airpack_input_topic',1,'']]],
  ['hxairpackinput_20tt_155',['&lt;tt&gt;HxAirpackInput&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_airpack_input',1,'']]],
  ['hxangulardof_156',['HxAngularDof',['../class_hx_angular_dof.html',1,'']]],
  ['hxangulardofserialized_157',['HxAngularDofSerialized',['../class_hx_angular_dof_serialized.html',1,'']]],
  ['hxassetmanager_158',['HxAssetManager',['../class_hx_asset_manager.html',1,'']]],
  ['hxassetmanager_2ecs_159',['HxAssetManager.cs',['../_hx_asset_manager_8cs.html',1,'']]],
  ['hxboundingvolume_160',['HxBoundingVolume',['../class_hx_bounding_volume.html',1,'']]],
  ['hxboundingvolume_2ecs_161',['HxBoundingVolume.cs',['../_hx_bounding_volume_8cs.html',1,'']]],
  ['hxboxboundingvolume_162',['HxBoxBoundingVolume',['../class_hx_box_bounding_volume.html',1,'']]],
  ['hxboxboundingvolume_2ecs_163',['HxBoxBoundingVolume.cs',['../_hx_box_bounding_volume_8cs.html',1,'']]],
  ['hxcharcoal_164',['HxCharcoal',['../class_hx_shared.html#a2384aded6184f842bded6b026f60e6f4',1,'HxShared']]],
  ['hxconstantmodel_165',['HxConstantModel',['../class_hx_constant_model.html',1,'']]],
  ['hxconstantmodelserialized_166',['HxConstantModelSerialized',['../class_hx_constant_model_serialized.html',1,'']]],
  ['hxcore_167',['HxCore',['../class_hx_core.html',1,'']]],
  ['hxcore_2ecs_168',['HxCore.cs',['../_hx_core_8cs.html',1,'']]],
  ['hxcurvedirecteffect_169',['HxCurveDirectEffect',['../class_hx_curve_direct_effect.html',1,'']]],
  ['hxcurvedirecteffect_2ecs_170',['HxCurveDirectEffect.cs',['../_hx_curve_direct_effect_8cs.html',1,'']]],
  ['hxcurvedirecteffecteditor_171',['HxCurveDirectEffectEditor',['../class_hx_curve_direct_effect_editor.html',1,'']]],
  ['hxcurvedirecteffecteditor_2ecs_172',['HxCurveDirectEffectEditor.cs',['../_hx_curve_direct_effect_editor_8cs.html',1,'']]],
  ['hxcurvemodel_173',['HxCurveModel',['../class_hx_curve_model.html',1,'']]],
  ['hxcurvemodelserialized_174',['HxCurveModelSerialized',['../class_hx_curve_model_serialized.html',1,'']]],
  ['hxcurveobjecteffect_175',['HxCurveObjectEffect',['../class_hx_curve_object_effect.html',1,'']]],
  ['hxcurveobjecteffect_2ecs_176',['HxCurveObjectEffect.cs',['../_hx_curve_object_effect_8cs.html',1,'']]],
  ['hxcurveobjecteffecteditor_177',['HxCurveObjectEffectEditor',['../class_hx_curve_object_effect_editor.html',1,'']]],
  ['hxcurveobjecteffecteditor_2ecs_178',['HxCurveObjectEffectEditor.cs',['../_hx_curve_object_effect_editor_8cs.html',1,'']]],
  ['hxcurvespatialeffect_179',['HxCurveSpatialEffect',['../class_hx_curve_spatial_effect.html',1,'']]],
  ['hxcurvespatialeffect_2ecs_180',['HxCurveSpatialEffect.cs',['../_hx_curve_spatial_effect_8cs.html',1,'']]],
  ['hxcurvespatialeffecteditor_181',['HxCurveSpatialEffectEditor',['../class_hx_curve_spatial_effect_editor.html',1,'']]],
  ['hxcurvespatialeffecteditor_2ecs_182',['HxCurveSpatialEffectEditor.cs',['../_hx_curve_spatial_effect_editor_8cs.html',1,'']]],
  ['hxcurvestatefunction_183',['HxCurveStateFunction',['../class_hx_curve_state_function.html',1,'HxCurveStateFunction'],['../class_hx_curve_state_function.html#af3eb805be2590053b42b36736fbae067',1,'HxCurveStateFunction.HxCurveStateFunction()']]],
  ['hxcurvestatefunctionserialized_184',['HxCurveStateFunctionSerialized',['../class_hx_curve_state_function_serialized.html',1,'']]],
  ['hxcylinderboundingvolume_185',['HxCylinderBoundingVolume',['../class_hx_cylinder_bounding_volume.html',1,'']]],
  ['hxcylinderboundingvolume_2ecs_186',['HxCylinderBoundingVolume.cs',['../_hx_cylinder_bounding_volume_8cs.html',1,'']]],
  ['hxdebug_187',['HxDebug',['../class_hx_debug.html',1,'']]],
  ['hxdebug_2ecs_188',['HxDebug.cs',['../_hx_debug_8cs.html',1,'']]],
  ['hxdebugdrawsystem_189',['HxDebugDrawSystem',['../class_hx_debug_draw_system.html',1,'']]],
  ['hxdebugmesh_190',['HxDebugMesh',['../class_hx_debug_mesh.html',1,'']]],
  ['hxdebugmesh_2ecs_191',['HxDebugMesh.cs',['../_hx_debug_mesh_8cs.html',1,'']]],
  ['hxdirecteffect_192',['HxDirectEffect',['../class_hx_direct_effect.html',1,'']]],
  ['hxdirecteffect_2ecs_193',['HxDirectEffect.cs',['../_hx_direct_effect_8cs.html',1,'']]],
  ['hxdof_194',['HxDof',['../class_hx_dof.html',1,'']]],
  ['hxdof_20tt_195',['&lt;tt&gt;HxDof&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_hx_dof',1,'']]],
  ['hxdof_2ecs_196',['HxDof.cs',['../_hx_dof_8cs.html',1,'']]],
  ['hxdofbehavior_197',['HxDofBehavior',['../class_hx_dof_behavior.html',1,'HxDofBehavior'],['../class_hx_dof_behavior.html#a30ff75d9bb37e5978dcf1a5d35c634b3',1,'HxDofBehavior.HxDofBehavior()']]],
  ['hxdofbehavior_20tt_198',['&lt;tt&gt;HxDofBehavior&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_hx_dof_behavior',1,'']]],
  ['hxdofbehavior_2ecs_199',['HxDofBehavior.cs',['../_hx_dof_behavior_8cs.html',1,'']]],
  ['hxdofbehaviorserialized_200',['HxDofBehaviorSerialized',['../class_hx_dof_behavior_serialized.html',1,'']]],
  ['hxdofbehaviorserialized_2ecs_201',['HxDofBehaviorSerialized.cs',['../_hx_dof_behavior_serialized_8cs.html',1,'']]],
  ['hxdofbehaviorserializedcontainer_202',['HxDofBehaviorSerializedContainer',['../class_hx_dof_behavior_serialized_container.html',1,'']]],
  ['hxdofbehaviortype_203',['HxDofBehaviorType',['../_hx_dof_behavior_8cs.html#ac1b00805bd3927a897991ccce97a1184',1,'HxDofBehavior.cs']]],
  ['hxdofbehaviortypeextensions_204',['HxDofBehaviorTypeExtensions',['../class_hx_dof_behavior_type_extensions.html',1,'']]],
  ['hxdofdefaultbehavior_205',['HxDofDefaultBehavior',['../class_hx_dof_default_behavior.html',1,'HxDofDefaultBehavior'],['../class_hx_dof_default_behavior.html#adeffa7bb50899912ea32e854f7b3bfb8',1,'HxDofDefaultBehavior.HxDofDefaultBehavior()']]],
  ['hxdofdefaultbehavior_2ecs_206',['HxDofDefaultBehavior.cs',['../_hx_dof_default_behavior_8cs.html',1,'']]],
  ['hxdofdefaultbehaviorserialized_207',['HxDofDefaultBehaviorSerialized',['../class_hx_dof_default_behavior_serialized.html',1,'']]],
  ['hxdofdetentbehavior_208',['HxDofDetentBehavior',['../class_hx_dof_detent_behavior.html',1,'HxDofDetentBehavior'],['../class_hx_dof_detent_behavior.html#a4cd37c83ac0935c98443252ebc784126',1,'HxDofDetentBehavior.HxDofDetentBehavior()']]],
  ['hxdofdetentbehavior_20tt_209',['&lt;tt&gt;HxDofDetentBehavior&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_hx_dof_detent_behavior',1,'']]],
  ['hxdofdetentbehavior_2ecs_210',['HxDofDetentBehavior.cs',['../_hx_dof_detent_behavior_8cs.html',1,'']]],
  ['hxdofdetentbehaviorserialized_211',['HxDofDetentBehaviorSerialized',['../class_hx_dof_detent_behavior_serialized.html',1,'HxDofDetentBehaviorSerialized'],['../class_hx_dof_detent_behavior_serialized.html#a0a870eb4b4491718cd8f3fe3f0813f27',1,'HxDofDetentBehaviorSerialized.HxDofDetentBehaviorSerialized()']]],
  ['hxdofs_212',['HxDofs',['../class_hx_dofs.html',1,'']]],
  ['hxdofs_2ecs_213',['HxDofs.cs',['../_hx_dofs_8cs.html',1,'']]],
  ['hxdofserialized_214',['HxDofSerialized',['../class_hx_dof_serialized.html',1,'']]],
  ['hxdofserialized_2ecs_215',['HxDofSerialized.cs',['../_hx_dof_serialized_8cs.html',1,'']]],
  ['hxdofserializedcontainer_216',['HxDofSerializedContainer',['../class_hx_dof_serialized_container.html',1,'']]],
  ['hxdoftargetpositionbehavior_217',['HxDofTargetPositionBehavior',['../class_hx_dof_target_position_behavior.html',1,'HxDofTargetPositionBehavior'],['../class_hx_dof_target_position_behavior.html#a8a772146c39ba23ab9b4404478930a80',1,'HxDofTargetPositionBehavior.HxDofTargetPositionBehavior()']]],
  ['hxdoftargetpositionbehavior_2ecs_218',['HxDofTargetPositionBehavior.cs',['../_hx_dof_target_position_behavior_8cs.html',1,'']]],
  ['hxdoftargetpositionbehaviorserialized_219',['HxDofTargetPositionBehaviorSerialized',['../class_hx_dof_target_position_behavior_serialized.html',1,'']]],
  ['hxerror_20tt_220',['&lt;tt&gt;HxError&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_error',1,'']]],
  ['hxfromunity_221',['HxFromUnity',['../class_hx_shared.html#afcdbcffec15da1cdc41fbc43200d8504',1,'HxShared.HxFromUnity(Vector2 v2, HaptxApi.Vector2D v2dOut)'],['../class_hx_shared.html#a36e6385957fe0015ce57777bf7ead884',1,'HxShared.HxFromUnity(Vector3 v3, HaptxApi.Vector3D v3dOut)'],['../class_hx_shared.html#a72fe7808ef8560c4eccbc3eb353dd680',1,'HxShared.HxFromUnity(Quaternion uq, HaptxApi.Quaternion qOut)'],['../class_hx_shared.html#afb49a380d53bb59d9d892759212fc925',1,'HxShared.HxFromUnity(Matrix4x4 um, HaptxApi.Transform mOut)'],['../class_hx_shared.html#a268abeb901f995b5c02e22423db8540f',1,'HxShared.HxFromUnity(Transform unityTransform, HaptxApi.Transform mOut)'],['../class_hx_shared.html#aa853120e88d2c5e091d36f38711626fd',1,'HxShared.HxFromUnity(Color unityColor, HaptxApi.Vector3D outHxColor)']]],
  ['hxfromunityangularvelocity_222',['HxFromUnityAngularVelocity',['../class_hx_shared.html#a5619290749541f81965b47349a659dc7',1,'HxShared']]],
  ['hxfromunityscale_223',['HxFromUnityScale',['../class_hx_shared.html#a529ff07c9cc305d949d90a4fe6b44720',1,'HxShared']]],
  ['hxg4config_224',['hxg4Config',['../class_hx_core.html#a5b449f50e956c81a291917ed75421b08',1,'HxCore']]],
  ['hxglobalsettingswindow_225',['HxGlobalSettingsWindow',['../class_hx_global_settings_window.html',1,'']]],
  ['hxglobalsettingswindow_2ecs_226',['HxGlobalSettingsWindow.cs',['../_hx_global_settings_window_8cs.html',1,'']]],
  ['hxgreen_227',['HxGreen',['../class_hx_shared.html#a8c67a4728e6b710c4442275638e38810',1,'HxShared']]],
  ['hxguilayout_228',['HxGUILayout',['../class_hx_g_u_i_layout.html',1,'']]],
  ['hxguilayout_2ecs_229',['HxGUILayout.cs',['../_hx_g_u_i_layout_8cs.html',1,'']]],
  ['hxguishared_230',['HxGUIShared',['../class_hx_g_u_i_shared.html',1,'']]],
  ['hxguishared_2ecs_231',['HxGUIShared.cs',['../_hx_g_u_i_shared_8cs.html',1,'']]],
  ['hxhand_232',['HxHand',['../class_hx_hand.html',1,'']]],
  ['hxhand_20tt_20script_233',['&lt;tt&gt;HxHand&lt;/tt&gt; Script',['../page_unity_plugin_summary.html#section_hx_hand_script',1,'']]],
  ['hxhand_2ecs_234',['HxHand.cs',['../_hx_hand_8cs.html',1,'']]],
  ['hxhandeditor_235',['HxHandEditor',['../class_hx_hand_editor.html',1,'']]],
  ['hxhandeditor_2ecs_236',['HxHandEditor.cs',['../_hx_hand_editor_8cs.html',1,'']]],
  ['hxhandsegment_237',['HxHandSegment',['../class_hx_hand_segment.html',1,'']]],
  ['hxhandsegment_2ecs_238',['HxHandSegment.cs',['../_hx_hand_segment_8cs.html',1,'']]],
  ['hxhapticeffect_239',['HxHapticEffect',['../class_hx_haptic_effect.html',1,'']]],
  ['hxhapticeffect_2ecs_240',['HxHapticEffect.cs',['../_hx_haptic_effect_8cs.html',1,'']]],
  ['hxhardwareinfo_241',['/HxHardwareInfo',['../page_ros_node_summary.html#section_hx_hardware_info_service',1,'']]],
  ['hxhardwareinfo_20tt_242',['&lt;tt&gt;HxHardwareInfo&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_hardware_info',1,'']]],
  ['hxinputsettingsrule_243',['HxInputSettingsRule',['../class_hx_input_settings_rule.html',1,'']]],
  ['hxinputsettingsrule_2ecs_244',['HxInputSettingsRule.cs',['../_hx_input_settings_rule_8cs.html',1,'']]],
  ['hxjoint_245',['HxJoint',['../class_hx_joint.html',1,'']]],
  ['hxjoint_20tt_246',['&lt;tt&gt;HxJoint&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_hx_joint',1,'']]],
  ['hxjoint_2ecs_247',['HxJoint.cs',['../_hx_joint_8cs.html',1,'']]],
  ['hxjointeditor_248',['HxJointEditor',['../class_hx_joint_editor.html',1,'']]],
  ['hxjointeditor_2ecs_249',['HxJointEditor.cs',['../_hx_joint_editor_8cs.html',1,'']]],
  ['hxlayer_250',['HxLayer',['../struct_hx_layer.html',1,'']]],
  ['hxlayer_2ecs_251',['HxLayer.cs',['../_hx_layer_8cs.html',1,'']]],
  ['hxlayerdrawer_252',['HxLayerDrawer',['../class_hx_layer_drawer.html',1,'']]],
  ['hxlayerdrawer_2ecs_253',['HxLayerDrawer.cs',['../_hx_layer_drawer_8cs.html',1,'']]],
  ['hxlineardof_254',['HxLinearDof',['../class_hx_linear_dof.html',1,'']]],
  ['hxlineardofserialized_255',['HxLinearDofSerialized',['../class_hx_linear_dof_serialized.html',1,'']]],
  ['hxlowpassfilter_256',['HxLowPassFilter',['../class_hx_low_pass_filter.html',1,'HxLowPassFilter'],['../class_hx_low_pass_filter.html#a0f07a578f31b2fc2a85257b2156015ad',1,'HxLowPassFilter.HxLowPassFilter()'],['../class_hx_low_pass_filter.html#a6bea4849352b094a87700544fa293cef',1,'HxLowPassFilter.HxLowPassFilter(float filterStrengthS)']]],
  ['hxlowpassfilter_2ecs_257',['HxLowPassFilter.cs',['../_hx_low_pass_filter_8cs.html',1,'']]],
  ['hxmath_258',['HxMath',['../class_hx_math.html',1,'']]],
  ['hxmocapdata_20tt_259',['&lt;tt&gt;HxMocapData&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_mocap_data',1,'']]],
  ['hxmocapdataraw_260',['/HxMocapDataRaw',['../page_ros_node_summary.html#section_hx_mocap_data_raw_topic',1,'']]],
  ['hxmocapdataworld_261',['/HxMocapDataWorld',['../page_ros_node_summary.html#section_hx_mocap_data_world_topic',1,'']]],
  ['hxmocapreceiverdata_20tt_262',['&lt;tt&gt;HxMocapReceiverData&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_mocap_receiver_data',1,'']]],
  ['hxname_263',['HxName',['../class_hx_name.html',1,'HxName'],['../class_hx_name.html#ad2cd61bce8fade8a98656b8ca21a48dc',1,'HxName.HxName()'],['../class_hx_name.html#a8045cbf49bf9579f5d851ba5316cf7a6',1,'HxName.HxName(string inString)'],['../class_hx_name.html#a2210006f6d8269e3d028bb02cf71fc0a',1,'HxName.HxName(HxName inName)']]],
  ['hxname_2ecs_264',['HxName.cs',['../_hx_name_8cs.html',1,'']]],
  ['hxnamedrawer_265',['HxNameDrawer',['../class_hx_name_drawer.html',1,'']]],
  ['hxnamedrawer_2ecs_266',['HxNameDrawer.cs',['../_hx_name_drawer_8cs.html',1,'']]],
  ['hxnetworkrigidbody_267',['HxNetworkRigidbody',['../class_hx_network_rigidbody.html',1,'']]],
  ['hxnetworkrigidbody_2ecs_268',['HxNetworkRigidbody.cs',['../_hx_network_rigidbody_8cs.html',1,'']]],
  ['hxnetworkrigidbodybase_269',['HxNetworkRigidbodyBase',['../class_hx_network_rigidbody_base.html',1,'']]],
  ['hxnetworkrigidbodybase_2ecs_270',['HxNetworkRigidbodyBase.cs',['../_hx_network_rigidbody_base_8cs.html',1,'']]],
  ['hxnetworkrigidbodychild_271',['HxNetworkRigidbodyChild',['../class_hx_network_rigidbody_child.html',1,'']]],
  ['hxnetworkrigidbodychild_2ecs_272',['HxNetworkRigidbodyChild.cs',['../_hx_network_rigidbody_child_8cs.html',1,'']]],
  ['hxnodeserializer_273',['HxNodeSerializer',['../class_hx_node_serializer.html',1,'']]],
  ['hxnodeserializer_2ecs_274',['HxNodeSerializer.cs',['../_hx_node_serializer_8cs.html',1,'']]],
  ['hxnodeserializer_3c_20hxdof_2c_20hxdofserialized_2c_20hxdofs_20_3e_275',['HxNodeSerializer&lt; HxDof, HxDofSerialized, HxDofs &gt;',['../class_hx_node_serializer.html',1,'']]],
  ['hxnodeserializer_3c_20hxdofbehavior_2c_20hxdofbehaviorserialized_2c_20hxdofs_20_3e_276',['HxNodeSerializer&lt; HxDofBehavior, HxDofBehaviorSerialized, HxDofs &gt;',['../class_hx_node_serializer.html',1,'']]],
  ['hxnodeserializer_3c_20hxphysicalmodel_2c_20hxphysicalmodelserialized_2c_20hxdofs_20_3e_277',['HxNodeSerializer&lt; HxPhysicalModel, HxPhysicalModelSerialized, HxDofs &gt;',['../class_hx_node_serializer.html',1,'']]],
  ['hxnodeserializer_3c_20hxstatefunction_2c_20hxstatefunctionserialized_2c_20hxdofs_20_3e_278',['HxNodeSerializer&lt; HxStateFunction, HxStateFunctionSerialized, HxDofs &gt;',['../class_hx_node_serializer.html',1,'']]],
  ['hxnstatefunction_279',['HxNStateFunction',['../class_hx_n_state_function.html',1,'HxNStateFunction'],['../class_hx_n_state_function.html#a813a197e0cf61848ca4661028953abb7',1,'HxNStateFunction.HxNStateFunction()']]],
  ['hxnstatefunctionserialized_280',['HxNStateFunctionSerialized',['../class_hx_n_state_function_serialized.html',1,'HxNStateFunctionSerialized'],['../class_hx_n_state_function_serialized.html#a4ad1397f71162bc629c2545081f85d85',1,'HxNStateFunctionSerialized.HxNStateFunctionSerialized()']]],
  ['hxobjecteffect_281',['HxObjectEffect',['../class_hx_object_effect.html',1,'']]],
  ['hxobjecteffect_2ecs_282',['HxObjectEffect.cs',['../_hx_object_effect_8cs.html',1,'']]],
  ['hxoffsettuner_283',['HxOffsetTuner',['../class_hx_offset_tuner.html',1,'']]],
  ['hxoffsettuner_2ecs_284',['HxOffsetTuner.cs',['../_hx_offset_tuner_8cs.html',1,'']]],
  ['hxonscreenlog_285',['HxOnScreenLog',['../class_hx_on_screen_log.html',1,'']]],
  ['hxonscreenlog_2ecs_286',['HxOnScreenLog.cs',['../_hx_on_screen_log_8cs.html',1,'']]],
  ['hxorange_287',['HxOrange',['../class_hx_shared.html#a3e71416f74ec90bbed76f6433feade01',1,'HxShared']]],
  ['hxpatch_288',['HxPatch',['../class_hx_patch.html',1,'']]],
  ['hxpatch_20tt_20script_289',['&lt;tt&gt;HxPatch&lt;/tt&gt; Script',['../page_unity_plugin_summary.html#section_hx_patch_script',1,'']]],
  ['hxpatch_2ecs_290',['HxPatch.cs',['../_hx_patch_8cs.html',1,'']]],
  ['hxpatchcomponenttactordata_291',['HxPatchComponentTactorData',['../struct_hx_patch_component_tactor_data.html',1,'HxPatchComponentTactorData'],['../struct_hx_patch_component_tactor_data.html#a74b27468d5fb2d31cac0393574f2d2a6',1,'HxPatchComponentTactorData::HxPatchComponentTactorData()']]],
  ['hxperipheral_20tt_292',['&lt;tt&gt;HxPeripheral&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_peripheral',1,'']]],
  ['hxphysicalmaterial_293',['HxPhysicalMaterial',['../class_hx_physical_material.html',1,'']]],
  ['hxphysicalmaterial_20tt_20script_294',['&lt;tt&gt;HxPhysicalMaterial&lt;/tt&gt; Script',['../page_unity_plugin_summary.html#section_unity_physical_material',1,'']]],
  ['hxphysicalmaterial_2ecs_295',['HxPhysicalMaterial.cs',['../_hx_physical_material_8cs.html',1,'']]],
  ['hxphysicalmaterialeditor_296',['HxPhysicalMaterialEditor',['../class_hx_physical_material_editor.html',1,'']]],
  ['hxphysicalmaterialeditor_2ecs_297',['HxPhysicalMaterialEditor.cs',['../_hx_physical_material_editor_8cs.html',1,'']]],
  ['hxphysicalmodel_298',['HxPhysicalModel',['../class_hx_physical_model.html',1,'']]],
  ['hxphysicalmodel_20tt_299',['&lt;tt&gt;HxPhysicalModel&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_hx_physical_model',1,'']]],
  ['hxphysicalmodels_2ecs_300',['HxPhysicalModels.cs',['../_hx_physical_models_8cs.html',1,'']]],
  ['hxphysicalmodelserialized_301',['HxPhysicalModelSerialized',['../class_hx_physical_model_serialized.html',1,'']]],
  ['hxphysicalmodelserialized_2ecs_302',['HxPhysicalModelSerialized.cs',['../_hx_physical_model_serialized_8cs.html',1,'']]],
  ['hxphysicalmodelserializedcontainer_303',['HxPhysicalModelSerializedContainer',['../class_hx_physical_model_serialized_container.html',1,'']]],
  ['hxphysicalmodeltype_304',['HxPhysicalModelType',['../_hx_physical_models_8cs.html#ad2a74a90766e82fa649bc52beb83f92b',1,'HxPhysicalModels.cs']]],
  ['hxphysicalmodeltypeextensions_305',['HxPhysicalModelTypeExtensions',['../class_hx_physical_model_type_extensions.html',1,'']]],
  ['hxphysicssettingsrules_2ecs_306',['HxPhysicsSettingsRules.cs',['../_hx_physics_settings_rules_8cs.html',1,'']]],
  ['hxplayer_307',['HxPlayer',['../class_hx_player.html',1,'']]],
  ['hxplayer_2ecs_308',['HxPlayer.cs',['../_hx_player_8cs.html',1,'']]],
  ['hxport_20tt_309',['&lt;tt&gt;HxPort&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_port',1,'']]],
  ['hxportpressure_20tt_310',['&lt;tt&gt;HxPortPressure&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_port_pressure',1,'']]],
  ['hxprimitivedebugger_311',['HxPrimitiveDebugger',['../class_hx_primitive_debugger.html',1,'']]],
  ['hxprimitivedebugger_2ecs_312',['HxPrimitiveDebugger.cs',['../_hx_primitive_debugger_8cs.html',1,'']]],
  ['hxrelayrecommendedsettingsrule_313',['HxRelayRecommendedSettingsRule',['../class_hx_relay_recommended_settings_rule.html',1,'HxRelayRecommendedSettingsRule'],['../class_hx_relay_recommended_settings_rule.html#a0e3c114ae682b6d0493665aefe4f31ac',1,'HxRelayRecommendedSettingsRule.HxRelayRecommendedSettingsRule()']]],
  ['hxrelaysettingsrule_2ecs_314',['HxRelaySettingsRule.cs',['../_hx_relay_settings_rule_8cs.html',1,'']]],
  ['hxreusableobjectpool_315',['HxReusableObjectPool',['../class_hx_reusable_object_pool.html',1,'']]],
  ['hxreusableobjectpool_2ecs_316',['HxReusableObjectPool.cs',['../_hx_reusable_object_pool_8cs.html',1,'']]],
  ['hxrigidbodycallbacks_317',['HxRigidbodyCallbacks',['../class_hx_rigidbody_callbacks.html',1,'HxRigidbodyCallbacks'],['../class_hx_rigidbody_callbacks.html#a66c3ea535184e13cd8b0cee5f4a00165',1,'HxRigidbodyCallbacks.HxRigidbodyCallbacks()']]],
  ['hxrigidbodyproperties_318',['HxRigidbodyProperties',['../class_hx_rigidbody_properties.html',1,'']]],
  ['hxrigidbodyproperties_20tt_20script_319',['&lt;tt&gt;HxRigidbodyProperties&lt;/tt&gt; Script',['../page_unity_plugin_summary.html#section_rigidbody_properties_script',1,'']]],
  ['hxrigidbodyproperties_2ecs_320',['HxRigidbodyProperties.cs',['../_hx_rigidbody_properties_8cs.html',1,'']]],
  ['hxrigidbodypropertieseditor_321',['HxRigidbodyPropertiesEditor',['../class_hx_rigidbody_properties_editor.html',1,'']]],
  ['hxrigidbodypropertieseditor_2ecs_322',['HxRigidbodyPropertiesEditor.cs',['../_hx_rigidbody_properties_editor_8cs.html',1,'']]],
  ['hxsetconstrainedcomponents_323',['hxSetConstrainedComponents',['../class_u_hx_constraint_component.html#a38b6b81a19af34236eb4e6e53c40c448',1,'UHxConstraintComponent']]],
  ['hxshared_324',['HxShared',['../class_hx_shared.html',1,'']]],
  ['hxshared_2ecs_325',['HxShared.cs',['../_hx_shared_8cs.html',1,'']]],
  ['hxsimulationcallbacks_2ecs_326',['HxSimulationCallbacks.cs',['../_hx_simulation_callbacks_8cs.html',1,'']]],
  ['hxsingleplayer_327',['HxSinglePlayer',['../class_hx_single_player.html',1,'']]],
  ['hxsingleplayer_2ecs_328',['HxSinglePlayer.cs',['../_hx_single_player_8cs.html',1,'']]],
  ['hxsleepmonitor_329',['HxSleepMonitor',['../class_hx_sleep_monitor.html',1,'']]],
  ['hxsleepmonitor_2ecs_330',['HxSleepMonitor.cs',['../_hx_sleep_monitor_8cs.html',1,'']]],
  ['hxspatialeffect_331',['HxSpatialEffect',['../class_hx_spatial_effect.html',1,'']]],
  ['hxspatialeffect_2ecs_332',['HxSpatialEffect.cs',['../_hx_spatial_effect_8cs.html',1,'']]],
  ['hxsphereboundingvolume_333',['HxSphereBoundingVolume',['../class_hx_sphere_bounding_volume.html',1,'']]],
  ['hxsphereboundingvolume_2ecs_334',['HxSphereBoundingVolume.cs',['../_hx_sphere_bounding_volume_8cs.html',1,'']]],
  ['hxspringmodel_335',['HxSpringModel',['../class_hx_spring_model.html',1,'']]],
  ['hxspringmodelserialized_336',['HxSpringModelSerialized',['../class_hx_spring_model_serialized.html',1,'']]],
  ['hxstatefunction_337',['HxStateFunction',['../class_hx_state_function.html',1,'HxStateFunction'],['../class_hx_state_function.html#ac942ac72a69c8c4f33206ce7438ee0a5',1,'HxStateFunction.HxStateFunction()']]],
  ['hxstatefunction_20tt_338',['&lt;tt&gt;HxStateFunction&lt;/tt&gt;',['../page_unity_haptic_primitive_summary.html#section_unity_hx_state_function',1,'']]],
  ['hxstatefunction_2ecs_339',['HxStateFunction.cs',['../_hx_state_function_8cs.html',1,'']]],
  ['hxstatefunctionserialized_340',['HxStateFunctionSerialized',['../class_hx_state_function_serialized.html',1,'']]],
  ['hxstatefunctionserialized_2ecs_341',['HxStateFunctionSerialized.cs',['../_hx_state_function_serialized_8cs.html',1,'']]],
  ['hxstatefunctionserializedcontainer_342',['HxStateFunctionSerializedContainer',['../class_hx_state_function_serialized_container.html',1,'']]],
  ['hxstatefunctiontype_343',['HxStateFunctionType',['../_hx_state_function_8cs.html#a13ac78477717e34e77a2be16c72affb3',1,'HxStateFunction.cs']]],
  ['hxstatefunctiontypeextensions_344',['HxStateFunctionTypeExtensions',['../class_hx_state_function_type_extensions.html',1,'']]],
  ['hxsteamvrsettings_345',['HxSteamVRSettings',['../class_hx_steam_v_r_settings.html',1,'']]],
  ['hxsteamvrsettings_2ecs_346',['HxSteamVRSettings.cs',['../_hx_steam_v_r_settings_8cs.html',1,'']]],
  ['hxstyles_347',['HxStyles',['../class_hx_styles.html',1,'']]],
  ['hxstyles_2ecs_348',['HxStyles.cs',['../_hx_styles_8cs.html',1,'']]],
  ['hxsurfacecomponent_349',['HxSurfaceComponent',['../class_hx_surface_component.html',1,'']]],
  ['hxsurfacecomponent_2ecs_350',['HxSurfaceComponent.cs',['../_hx_surface_component_8cs.html',1,'']]],
  ['hxsurfacecomponenteditor_351',['HxSurfaceComponentEditor',['../class_hx_surface_component_editor.html',1,'']]],
  ['hxsurfacecomponenteditor_2ecs_352',['HxSurfaceComponentEditor.cs',['../_hx_surface_component_editor_8cs.html',1,'']]],
  ['hxteal_353',['HxTeal',['../class_hx_shared.html#a8431e358e4c98d286ba1d9772a2015da',1,'HxShared']]],
  ['hxtimesettingsrules_2ecs_354',['HxTimeSettingsRules.cs',['../_hx_time_settings_rules_8cs.html',1,'']]],
  ['hxtrackerdata_20tt_355',['&lt;tt&gt;HxTrackerData&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_tracker_data',1,'']]],
  ['hxtrackermount_20tt_356',['&lt;tt&gt;HxTrackerMount&lt;/tt&gt;',['../page_ros_node_summary.html#section_hx_tracker_mount',1,'']]],
  ['hxtransformcallbacks_357',['HxTransformCallbacks',['../class_hx_transform_callbacks.html',1,'HxTransformCallbacks'],['../class_hx_transform_callbacks.html#a3514e2a2f8e354f0ba1aec9b94817e6d',1,'HxTransformCallbacks.HxTransformCallbacks()']]],
  ['hxunitysettingswindow_358',['HxUnitySettingsWindow',['../class_hx_unity_settings_window.html',1,'']]],
  ['hxunitysettingswindow_2ecs_359',['HxUnitySettingsWindow.cs',['../_hx_unity_settings_window_8cs.html',1,'']]],
  ['hxunrealeffect_360',['HxUnrealEffect',['../class_u_hx_haptic_effect_component_1_1_hx_unreal_effect.html',1,'UHxHapticEffectComponent::HxUnrealEffect&lt; hx_effect_t, ue_comp_t &gt;'],['../class_u_hx_haptic_effect_component_1_1_hx_unreal_effect.html#ae58e8dedf230f854786600f02db6346b',1,'UHxHapticEffectComponent::HxUnrealEffect::HxUnrealEffect()']]],
  ['hxupdate_361',['HxUpdate',['../interface_hx_core_1_1_i_hx_update.html#af9c9400e183b2a13dcc55f217cddd907',1,'HxCore.IHxUpdate.HxUpdate()'],['../class_hx_hand.html#adffa8a3399599357e15276082d75e465',1,'HxHand.HxUpdate()'],['../class_hx_patch.html#a31ddc1221ddd12466666a156d5991bcf',1,'HxPatch.HxUpdate()']]],
  ['hxversioncompatability_362',['HxVersionCompatability',['../class_hx_version_compatability.html',1,'']]],
  ['hxversioncompatability_2ecs_363',['HxVersionCompatability.cs',['../_hx_version_compatability_8cs.html',1,'']]],
  ['hxvisualizer_364',['HxVisualizer',['../class_hx_visualizer.html',1,'HxVisualizer'],['../class_hx_visualizer.html#aa1b69e346cb89200ffb30ffa1cfee43e',1,'HxVisualizer.HxVisualizer()'],['../class_hx_visualizer.html#a8380da86b8941a3d61873050902edcdc',1,'HxVisualizer.HxVisualizer(KeyCode key, bool alt, bool shift, bool control)']]],
  ['hxvisualizer_2ecs_365',['HxVisualizer.cs',['../_hx_visualizer_8cs.html',1,'']]],
  ['hxwavedirecteffect_366',['HxWaveDirectEffect',['../class_hx_wave_direct_effect.html',1,'HxWaveDirectEffect'],['../class_hx_wave_direct_effect.html#a95d6235a75b892fa78c7f2326cf8c190',1,'HxWaveDirectEffect.HxWaveDirectEffect()']]],
  ['hxwavedirecteffect_2ecs_367',['HxWaveDirectEffect.cs',['../_hx_wave_direct_effect_8cs.html',1,'']]],
  ['hxwaveobjecteffect_368',['HxWaveObjectEffect',['../class_hx_wave_object_effect.html',1,'HxWaveObjectEffect'],['../class_hx_wave_object_effect.html#a876f9e0e01654d538ebee5dbae7a3c30',1,'HxWaveObjectEffect.HxWaveObjectEffect()']]],
  ['hxwaveobjecteffect_2ecs_369',['HxWaveObjectEffect.cs',['../_hx_wave_object_effect_8cs.html',1,'']]],
  ['hxwavespatialeffect_370',['HxWaveSpatialEffect',['../class_hx_wave_spatial_effect.html',1,'HxWaveSpatialEffect'],['../class_hx_wave_spatial_effect.html#abbf7bc0af9c331ae3e4d933e559ef37f',1,'HxWaveSpatialEffect.HxWaveSpatialEffect()']]],
  ['hxwavespatialeffect_2ecs_371',['HxWaveSpatialEffect.cs',['../_hx_wave_spatial_effect_8cs.html',1,'']]],
  ['hxyellow_372',['HxYellow',['../class_hx_shared.html#a6c389fb17eeb68635ecb1318a6380d2c',1,'HxShared']]]
];
